name: iOS starter workflow

on:
  push:
    branches: [ "develop", "feature/**", "release/**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: â¬‡ï¸ Checkout â¬‡ï¸
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ğŸª› Install dependencies ğŸª›
        run: bundle install